#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Curriculum Vitae
email: david.dilanchian@pm.pm
url: 'https://david-dilan.github.io/cv/'
baseurl: '/cv/' #change it according to your repository name
description: Tell me and I forget. Teach me and I remember. Involve me and I learn.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: 5e5e5e #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-144097749-1
analytics: 'UA-145453835-1'
google_analytics: "UA-144097749-1"
google_analytics: "UA-145453835-1"



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
